#!/usr/bin/env node
const npxFlagIndex = process.env.ASTRA_DEV === '1' ? process.argv.indexOf('--npx') : -1;

if (npxFlagIndex === -1) {
  process.env.ASTRA_LOCAL = '1';
} else {
  process.argv.splice(npxFlagIndex, 1);
}

import('./apps/cli/dist/index.mjs');
